### ISSUE TITLE
Getting stuck when trying to train

### ISSUE THREAD

**Issue by ghost** [MhLiao/MaskTextSpotter#5]
@MhLiao Thank you for your hard work,

When trying to train using the [`Pretrain`](https://github.com/MhLiao/MaskTextSpotter#pretrain) command, an error is shown `invalid device ordinal`, then it gets stuck after loading the config. The log is attached here [log.txt](https://github.com/MhLiao/MaskTextSpotter/files/3748395/log.txt)

My MaskTextSpotter is installed correctly, the `sh test.sh`functions properly without any issue.
My system specification: Ubuntu 18.04/ 16GB RAM/ GTX 1070 ti 8GB/ GTX 960 4GB/ ryzen 2600

The training log:
```
(mask) home@home-desktop:~/p5/MaskTextSpotter$ python3 -m torch.distributed.launch --nproc_per_node=8 tools/train_net.py --config-file configs/pretrain.yaml
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1570710853631/work/torch/csrc/cuda/Module.cpp line=37 error=10 : invalid device ordinal
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1570710853631/work/torch/csrc/cuda/Module.cpp line=37 error=10 : invalid device ordinal
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1570710853631/work/torch/csrc/cuda/Module.cpp line=37 error=10 : invalid device ordinal
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1570710853631/work/torch/csrc/cuda/Module.cpp line=37 error=10 : invalid device ordinal
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1570710853631/work/torch/csrc/cuda/Module.cpp line=37 error=10 : invalid device ordinal
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1570710853631/work/torch/csrc/cuda/Module.cpp line=37 error=10 : invalid device ordinal
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "tools/train_net.py", line 173, in <module>
  File "tools/train_net.py", line 173, in <module>
  File "tools/train_net.py", line 173, in <module>
Traceback (most recent call last):
  File "tools/train_net.py", line 173, in <module>
    main()
  File "tools/train_net.py", line 140, in main
    main()
  File "tools/train_net.py", line 140, in main
    main()
    torch.cuda.set_device(args.local_rank)
  File "tools/train_net.py", line 140, in main
Traceback (most recent call last):
  File "/home/home/anaconda3/envs/mask/lib/python3.6/site-packages/torch/cuda/__init__.py", line 300, in set_device
  File "tools/train_net.py", line 173, in <module>
    main()
  File "tools/train_net.py", line 140, in main
    torch._C._cuda_setDevice(device)
    torch.cuda.set_device(args.local_rank)
Traceback (most recent call last):
  File "/home/home/anaconda3/envs/mask/lib/python3.6/site-packages/torch/cuda/__init__.py", line 300, in set_device
RuntimeError: cuda runtime error (10) : invalid device ordinal at /opt/conda/conda-bld/pytorch_1570710853631/work/torch/csrc/cuda/Module.cpp:37
  File "tools/train_net.py", line 173, in <module>
    torch.cuda.set_device(args.local_rank)
    torch.cuda.set_device(args.local_rank)
  File "/home/home/anaconda3/envs/mask/lib/python3.6/site-packages/torch/cuda/__init__.py", line 300, in set_device
  File "/home/home/anaconda3/envs/mask/lib/python3.6/site-packages/torch/cuda/__init__.py", line 300, in set_device
    main()
  File "tools/train_net.py", line 140, in main
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (10) : invalid device ordinal at /opt/conda/conda-bld/pytorch_1570710853631/work/torch/csrc/cuda/Module.cpp:37
    main()
  File "tools/train_net.py", line 140, in main
    torch._C._cuda_setDevice(device)
    torch.cuda.set_device(args.local_rank)
RuntimeError: cuda runtime error (10) : invalid device ordinal at /opt/conda/conda-bld/pytorch_1570710853631/work/torch/csrc/cuda/Module.cpp:37
    torch._C._cuda_setDevice(device)
  File "/home/home/anaconda3/envs/mask/lib/python3.6/site-packages/torch/cuda/__init__.py", line 300, in set_device
RuntimeError: cuda runtime error (10) : invalid device ordinal at /opt/conda/conda-bld/pytorch_1570710853631/work/torch/csrc/cuda/Module.cpp:37
    torch.cuda.set_device(args.local_rank)
  File "/home/home/anaconda3/envs/mask/lib/python3.6/site-packages/torch/cuda/__init__.py", line 300, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (10) : invalid device ordinal at /opt/conda/conda-bld/pytorch_1570710853631/work/torch/csrc/cuda/Module.cpp:37
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (10) : invalid device ordinal at /opt/conda/conda-bld/pytorch_1570710853631/work/torch/csrc/cuda/Module.cpp:37
2019-10-20 23:27:37,465 maskrcnn_benchmark INFO: Using 8 GPUs
2019-10-20 23:27:37,465 maskrcnn_benchmark INFO: Namespace(config_file='configs/pretrain.yaml', distributed=True, local_rank=0, opts=[], skip_test=False)
2019-10-20 23:27:37,466 maskrcnn_benchmark INFO: Collecting env info (might take some time)
2019-10-20 23:27:38,570 maskrcnn_benchmark INFO: 
PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Linux Mint 19.2 Tina
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: 
GPU 0: GeForce GTX 1070 Ti
GPU 1: GeForce GTX 960

Nvidia driver version: 418.74
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.17.3
[pip] torch==1.3.0
[pip] torchvision==0.4.1a0+d94043a
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py36he904b0f_0  
[conda] mkl_fft                   1.0.14           py36ha843d7b_0  
[conda] mkl_random                1.1.0            py36hd6b4f25_0  
[conda] pytorch                   1.3.0           py3.6_cuda10.0.130_cudnn7.6.3_0    pytorch
[conda] torchvision               0.4.1                py36_cu100    pytorch
        Pillow (6.2.0)
2019-10-20 23:27:38,570 maskrcnn_benchmark INFO: Loaded configuration file configs/pretrain.yaml
2019-10-20 23:27:38,570 maskrcnn_benchmark INFO: 
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  # WEIGHT: "./outputs/synth_pretrain_shrink++/model_0270000.pth"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
    BATCH_SIZE_PER_IMAGE: 512
  ROI_BOX_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 2
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "SeqCharMaskRCNNC4Predictor"
    POOLER_RESOLUTION_H: 16
    POOLER_RESOLUTION_W: 64
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    RESOLUTION_H: 32
    RESOLUTION_W: 128
    SHARE_BOX_FEATURE_EXTRACTOR: False
    CHAR_NUM_CLASSES: 37
    USE_WEIGHTED_CHAR_MASK: True
    MASK_BATCH_SIZE_PER_IM: 64
  MASK_ON: True
  CHAR_MASK_ON: True
SEQUENCE:
  SEQ_ON: False
  NUM_CHAR: 38
  BOS_TOKEN: 0
  MAX_LENGTH: 32
  TEACHER_FORCE_RATIO: 1.0
  TWO_CONV: True
DATASETS:
  TRAIN: ("icdar_2015_train",)
  TEST: ("icdar_2015_test",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
  NUM_WORKERS: 4
  ASPECT_RATIO_GROUPING: False
SOLVER:
  BASE_LR: 0.01 #0.02
  WARMUP_FACTOR: 0.1
  WEIGHT_DECAY: 0.0001
  STEPS: (100000, 160000)
  MAX_ITER: 300000
  IMS_PER_BATCH: 4
OUTPUT_DIR: "./outputs/pretrain"
TEST:
  VIS: False
  CHAR_THRESH: 192
  IMS_PER_BATCH: 1
INPUT:
  MIN_SIZE_TRAIN: (600, 800)
  MAX_SIZE_TRAIN: 2333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333

2019-10-20 23:27:38,571 maskrcnn_benchmark INFO: Running with config:
DATALOADER:
  ASPECT_RATIO_GROUPING: False
  NUM_WORKERS: 4
  SIZE_DIVISIBILITY: 32
DATASETS:
  AUG: False
  RANDOM_CROP_PROB: 0.0
  RATIOS: []
  TEST: ('icdar_2015_test',)
  TRAIN: ('icdar_2015_train',)
INPUT:
  MAX_SIZE_TEST: 1333
  MAX_SIZE_TRAIN: 2333
  MIN_SIZE_TEST: 800
  MIN_SIZE_TRAIN: (600, 800)
  PIXEL_MEAN: [102.9801, 115.9465, 122.7717]
  PIXEL_STD: [1.0, 1.0, 1.0]
  TO_BGR255: True
MODEL:
  BACKBONE:
    CONV_BODY: R-50-FPN
    FREEZE_CONV_BODY_AT: 2
    OUT_CHANNELS: 256
  CHAR_MASK_ON: True
  DEVICE: cuda
  MASK_ON: True
  META_ARCHITECTURE: GeneralizedRCNN
  RESNETS:
    NUM_GROUPS: 1
    RES2_OUT_CHANNELS: 256
    RES5_DILATION: 1
    STEM_FUNC: StemWithFixedBatchNorm
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: True
    TRANS_FUNC: BottleneckWithFixedBatchNorm
    WIDTH_PER_GROUP: 64
  ROI_BOX_HEAD:
    FEATURE_EXTRACTOR: FPN2MLPFeatureExtractor
    MLP_HEAD_DIM: 1024
    NUM_CLASSES: 2
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    PREDICTOR: FPNPredictor
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 512
    BBOX_REG_WEIGHTS: (10.0, 10.0, 5.0, 5.0)
    BG_IOU_THRESHOLD: 0.5
    DETECTIONS_PER_IMG: 100
    FG_IOU_THRESHOLD: 0.5
    NMS: 0.5
    POSITIVE_FRACTION: 0.25
    SCORE_THRESH: 0.05
    USE_FPN: True
  ROI_MASK_HEAD:
    CHAR_NUM_CLASSES: 37
    CONV_LAYERS: (256, 256, 256, 256)
    FEATURE_EXTRACTOR: MaskRCNNFPNFeatureExtractor
    MASK_BATCH_SIZE_PER_IM: 64
    MLP_HEAD_DIM: 1024
    POOLER_RESOLUTION: 14
    POOLER_RESOLUTION_H: 16
    POOLER_RESOLUTION_W: 64
    POOLER_SAMPLING_RATIO: 2
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    PREDICTOR: SeqCharMaskRCNNC4Predictor
    RESOLUTION: 28
    RESOLUTION_H: 32
    RESOLUTION_W: 128
    SHARE_BOX_FEATURE_EXTRACTOR: False
    USE_WEIGHTED_CHAR_MASK: True
  RPN:
    ANCHOR_SIZES: (32, 64, 128, 256, 512)
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    ASPECT_RATIOS: (0.5, 1.0, 2.0)
    BATCH_SIZE_PER_IMAGE: 256
    BG_IOU_THRESHOLD: 0.3
    FG_IOU_THRESHOLD: 0.7
    FPN_POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TRAIN: 2000
    MIN_SIZE: 0
    NMS_THRESH: 0.7
    POSITIVE_FRACTION: 0.5
    POST_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    PRE_NMS_TOP_N_TRAIN: 2000
    STRADDLE_THRESH: 0
    USE_FPN: True
  RPN_ONLY: False
  WEIGHT: catalog://ImageNetPretrained/MSRA/R-50
OUTPUT_DIR: ./outputs/pretrain
PATHS_CATALOG: /home/home/p5/MaskTextSpotter/maskrcnn_benchmark/config/paths_catalog.py
SEQUENCE:
  BOS_TOKEN: 0
  MAX_LENGTH: 32
  MEAN_SCORE: False
  NUM_CHAR: 38
  SEQ_ON: False
  TEACHER_FORCE_RATIO: 1.0
  TWO_CONV: True
SOLVER:
  BASE_LR: 0.01
  BIAS_LR_FACTOR: 2
  CHECKPOINT_PERIOD: 2500
  GAMMA: 0.1
  IMS_PER_BATCH: 4
  MAX_ITER: 300000
  MOMENTUM: 0.9
  RESUME: True
  STEPS: (100000, 160000)
  USE_ADAM: False
  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 500
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0
TEST:
  CHAR_THRESH: 192
  EXPECTED_RESULTS: []
  EXPECTED_RESULTS_SIGMA_TOL: 4
  IMS_PER_BATCH: 1
  VIS: False

```

**Comment by ghost** [comment]
The issue was caused because it was using 8 gpus by default.
I changed `--nproc_per_node=8` to `--nproc_per_node=1` 
now it only uses 1 gpu

**Comment by sno6** [comment]
Hey @deepseek, I am running into this problem when trying to train with 2 GPUs. I have set `--nproc_per_node` to `2` and it just hangs here.
